/**
 * Generates `src/courses/istorija-srbije-365/_generated.ts` from the
 * authoritative JSON content at `<repo-root>/content/courses/istorija-srbije-365/`.
 *
 * The registry imports the generated file at module load time, so the data
 * ends up in the JS bundle — no `node:fs` at runtime, no client/server split
 * to worry about. The JSON files are the source of truth; this script just
 * makes them visible to the bundler.
 *
 * Run via `pnpm gen-content` (root) or `pnpm --filter @learn365/content gen-content`.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadCourseFromFiles } from '../src/loader/index.js';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(SCRIPT_DIR, '..');
const REPO_ROOT = resolve(PACKAGE_ROOT, '..', '..');

const COURSE_ID = 'istorija-srbije-365';
const SOURCE_DIR = join(REPO_ROOT, 'content', 'courses', COURSE_ID);
const OUT_FILE = join(
  PACKAGE_ROOT,
  'src',
  'courses',
  COURSE_ID,
  '_generated.ts',
);

function header(sourceDir: string): string {
  return `// AUTO-GENERATED by packages/content/scripts/gen-content.ts.
// Source of truth: ${sourceDir.replace(/\\/g, '/')}
// Do not edit by hand — re-run \`pnpm gen-content\` after editing the JSON.
`;
}

function emit(): void {
  const loaded = loadCourseFromFiles(SOURCE_DIR);

  const body = `${header(`content/courses/${COURSE_ID}`)}
import type { Course, Era, Lesson, Section } from '../../types.js';

export const course: Course = ${JSON.stringify(loaded.course, null, 2)};

export const eras: readonly Era[] = ${JSON.stringify(loaded.eras, null, 2)};

export const sections: readonly Section[] = ${JSON.stringify(loaded.sections, null, 2)};

export const lessons: readonly Lesson[] = ${JSON.stringify(loaded.lessons, null, 2)};
`;

  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, body, 'utf8');

  console.log(
    `@learn365/content: wrote ${OUT_FILE.replace(REPO_ROOT, '.')} ` +
      `(${String(loaded.lessons.length)} lessons, ${String(loaded.sections.length)} sections, ${String(loaded.eras.length)} eras)`,
  );
}

emit();
