/**
 * Generates two modules under `src/courses/istorija-srbije-365/` from the
 * authoritative JSON content at `<repo-root>/content/courses/istorija-srbije-365/`:
 *
 * - `_generated.ts` — course, eras, sections and the lesson *summaries*
 *   (`LessonSummary[]`, the navigation index). Imported by the registry, so
 *   it ends up in every bundle, client included; kept small on purpose.
 * - `_generated.articles.ts` — the lesson *articles* (body, sources, byline,
 *   …) keyed by lesson id. Reachable only through `@learn365/content/server`.
 *
 * Both come from one load, so they cannot drift from each other. No
 * `node:fs` at runtime: the JSON files are the source of truth and this
 * script just makes them visible to the bundler.
 *
 * Run via `pnpm gen-content` (root) or `pnpm --filter @learn365/content gen-content`.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadCourseFromFiles } from '../src/loader/index.js';
import { LESSON_ARTICLE_KEYS, type Lesson } from '../src/types.js';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(SCRIPT_DIR, '..');
const REPO_ROOT = resolve(PACKAGE_ROOT, '..', '..');

const COURSE_ID = 'istorija-srbije-365';
const SOURCE_DIR = join(REPO_ROOT, 'content', 'courses', COURSE_ID);
const OUT_DIR = join(PACKAGE_ROOT, 'src', 'courses', COURSE_ID);
const SUMMARIES_FILE = join(OUT_DIR, '_generated.ts');
const ARTICLES_FILE = join(OUT_DIR, '_generated.articles.ts');

const ARTICLE_KEYS: ReadonlySet<string> = new Set(LESSON_ARTICLE_KEYS);

function header(sourceDir: string): string {
  return `// AUTO-GENERATED by packages/content/scripts/gen-content.ts.
// Source of truth: ${sourceDir.replace(/\\/g, '/')}
// Do not edit by hand — re-run \`pnpm gen-content\` after editing the JSON.
`;
}

/**
 * One lesson → its client-safe summary and its server-only article, split on
 * `LESSON_ARTICLE_KEYS` (the same constant the types are derived from).
 */
function splitLesson(lesson: Lesson): {
  summary: Record<string, unknown>;
  article: Record<string, unknown>;
} {
  const summary: Record<string, unknown> = {};
  const article: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(lesson)) {
    if (ARTICLE_KEYS.has(key)) article[key] = value;
    else summary[key] = value;
  }
  return { summary, article };
}

function emit(): void {
  const loaded = loadCourseFromFiles(SOURCE_DIR);
  const split = loaded.lessons.map((lesson) => ({ id: lesson.id, ...splitLesson(lesson) }));
  const summaries = split.map((entry) => entry.summary);
  const articles = Object.fromEntries(split.map((entry) => [entry.id, entry.article]));

  const summariesBody = `${header(`content/courses/${COURSE_ID}`)}
import type { Course, Era, LessonSummary, Section } from '../../types.js';

export const course: Course = ${JSON.stringify(loaded.course, null, 2)};

export const eras: readonly Era[] = ${JSON.stringify(loaded.eras, null, 2)};

export const sections: readonly Section[] = ${JSON.stringify(loaded.sections, null, 2)};

export const lessons: readonly LessonSummary[] = ${JSON.stringify(summaries, null, 2)};
`;

  const articlesBody = `${header(`content/courses/${COURSE_ID}`)}
// Server-only. Reached through \`@learn365/content/server\` (which carries
// \`import 'server-only'\`); never import this module from client code.

import type { LessonArticle, LessonId } from '../../types.js';

export const articles: Readonly<Record<LessonId, LessonArticle>> = ${JSON.stringify(articles, null, 2)};
`;

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(SUMMARIES_FILE, summariesBody, 'utf8');
  writeFileSync(ARTICLES_FILE, articlesBody, 'utf8');

  console.log(
    `@learn365/content: wrote ${SUMMARIES_FILE.replace(REPO_ROOT, '.')} + ${ARTICLES_FILE.replace(REPO_ROOT, '.')} ` +
      `(${String(loaded.lessons.length)} lessons, ${String(loaded.sections.length)} sections, ${String(loaded.eras.length)} eras)`,
  );
}

emit();
