import type { SectionId } from '../../../types.js';

/**
 * Curated lesson titles per section. Array length must equal that
 * section's lesson count (`endDay - startDay + 1`). The validator
 * enforces this.
 *
 * Titles drive the sidebar at full scale before lesson bodies are
 * authored. Many are ported from the Cloud Design V1 prototype's
 * `LESSON_TITLES` and rounded out for sections the prototype didn't
 * cover at full depth.
 */
export const lessonTitles: Record<SectionId, readonly string[]> = {
  // ───────────────── Era I — Rani srednji vek ─────────────────
  'praistorija-i-antika': [
    'Lepenski Vir',
    'Vinčanska kultura',
    'Iliri na zapadnom Balkanu',
    'Tračani na istoku',
    'Keltske grupe',
    'Rimsko osvajanje Ilirika',
    'Provincije Moesia i Dalmacija',
    'Konstantin Veliki i Naissus',
    'Hrišćanstvo na rimskom Balkanu',
    'Justinijan i istočno Rimsko carstvo',
  ],
  'doseljavanje-slovena': [
    'Sloveni pre dolaska na Balkan',
    'Velike seobe i prvi tragovi Srba',
    'Avarski pohodi',
    'Heraklije i naseljavanje Srba',
    'Konstantin Porfirogenit o Srbima',
    'Pokrštavanje i prvi episkopi',
    'Knez Višeslav i prve župe',
    'Časlav Klonimirović i Raška',
    'Ćirilo i Metodije',
    'Vizantija u IX i X veku',
  ],
  'prve-knezevine': [
    'Duklja u XI veku',
    'Kralj Mihailo Vojislavljević',
    'Bodin i kratko ujedinjenje',
    'Stefan Vojislav protiv Vizantije',
    'Letopis popa Dukljanina',
    'Veliki župani Raške',
    'Zavidovići — Vukan, Stracimir, Nemanja',
    'Sukob braće',
    'Tihomir i mlađi brat Nemanja',
    'Bitka kod Pantina',
  ],

  // ───────────────── Era II — Nemanjići ─────────────────
  'rani-nemanjici': [
    'Stefan Nemanja preuzima vlast',
    'Sabor u Rasu i jeretici',
    'Sukob sa Vizantijom',
    'Osnivanje Studenice',
    'Nemanjino odricanje od vlasti',
    'Hilandar — kuća srpske duhovnosti',
    'Rastko odlazi na Svetu Goru',
    'Smrt Simeona Mirotočivog',
    'Stefan Prvovenčani na prestolu',
    'Žička povelja',
    'Kraljevska kruna 1217.',
    'Sveti Sava u Nikejskoj crkvi',
    'Autokefalnost srpske crkve 1219.',
    '„Život svetog Simeona"',
    'Smrt Stefana Prvovenčanog',
  ],
  'sredina-xiii-veka': [
    'Kralj Stefan Radoslav',
    'Vladislav i bitka kod Klokotnice',
    'Mileševa i prenos moštiju',
    'Smrt svetog Save',
    'Kralj Uroš I',
    'Borba sa Mađarskom',
    'Mati Jelena Anžujska',
    'Manastir Sopoćani',
    'Sabor protiv Uroša I',
    'Dragutin preuzima vlast',
  ],
  'milutin-i-decanski': [
    'Kralj Dragutin',
    'Padom s konja u Deževu',
    'Milutin postaje kralj',
    'Brak sa Simonidom',
    'Borbe sa Vizantijom',
    'Banjska zadužbina',
    'Gračanica',
    'Studenica Hvostanska',
    'Smrt kralja Milutina',
    'Stefan Dečanski osvaja presto',
    'Bitka kod Velbužda 1330.',
    'Visoki Dečani',
    'Manastirska škola Dečana',
    'Otac protiv sina',
    'Smrt Stefana Dečanskog',
  ],
  'dusanovo-carstvo': [
    'Dušan postaje kralj',
    'Osvajanja na jugu',
    'Sabor u Skoplju 1346.',
    'Krunisanje za cara',
    'Patrijaršija u Peći',
    'Dušanov zakonik — prvi deo',
    'Dušanov zakonik — drugi deo',
    'Carstvo dvojezičnog poretka',
    'Saradnja sa Atosom',
    'Bitka kod Stefanijane',
    'Pohodi na Vizantiju',
    'Diplomatske igre sa Mletcima',
    'Dušanovi velikaši',
    'Carica Jelena',
    'Manastir Lesnovo',
    'Velika seoba na jug',
    'Posete Hilandaru',
    'Smrt cara Dušana 1355.',
    'Šta je Dušan ostavio',
    'Carstvo u jednoj generaciji',
  ],
  'pad-carstva': [
    'Car Uroš Nejaki',
    'Borba velikaša',
    'Vukašin Mrnjavčević',
    'Despot Uglješa',
    'Bitka na Marici 1371.',
    'Smrt cara Uroša',
    'Raspad carstva',
    'Knez Lazar dolazi',
    'Vuk Branković',
    'Đurađ Balšić',
    'Bosna pod Tvrtkom',
    'Sukobi velikaša',
    'Kratak savez sa Bosnom',
    'Knez Lazar i crkva',
    'Most ka Kosovu',
  ],

  // ───────────────── Era III — Despotovina ─────────────────
  'moravska-srbija-i-kosovo': [
    'Moravska Srbija',
    'Lazar i njegove zadužbine',
    'Ravanica',
    'Saradnja sa Vukom Brankovićem',
    'Murat I dolazi',
    'Bitka na Kosovu — uoči',
    '15. jun 1389.',
    'Posle bitke',
    'Smrt kneza Lazara',
    'Kneginja Milica preuzima vlast',
  ],
  'despot-stefan': [
    'Stefan Lazarević mladi',
    'Vazalstvo prema Bajazitu',
    'Bitka kod Angore 1402.',
    'Despotsko zvanje od Vizantije',
    'Beograd kao prestonica',
    '„Slovo ljubve"',
    'Despot — vitez i pesnik',
    'Manastir Manasija',
    'Resava — kulturni centar',
    'Smrt despota Stefana',
  ],
  'djuradj-brankovic': [
    'Đurađ Branković preuzima despotovinu',
    'Smederevo — nova prestonica',
    'Mara Branković',
    'Pohodi Murata II',
    'Janoš Hunjadi i savez',
    'Dugi rat 1443-44.',
    'Mehmed II osvajač',
    'Opsada Smedereva',
    'Pad Smedereva 1459.',
    'Kraj srednjovekovne Srbije',
  ],

  // ───────────────── Era IV — Pod osmanlijama ─────────────────
  'zivot-pod-sultanom': [
    'Posle pada — prvi decenij',
    'Sandžaci i timari',
    'Devširma i janičari',
    'Spahije i raja',
    'Selo i porez',
    'Hrišćanski milet',
    'Zemlja, ali ne i mač',
    'Ćirilične štampane knjige',
    'Bosna i hercegovačka begovat',
    'Crna Gora — vladike',
    'Crnogorska sloboda',
    'Stari karavan-put',
  ],
  'pecka-patrijarsija': [
    'Pad Pećke patrijaršije',
    'Obnova 1557.',
    'Makarije Sokolović',
    'Mehmed-paša Sokolović',
    'Most na Drini',
    'Crkva pod vlašću sultana',
    'Srpsko ikonopisanje XVI veka',
    'Manastiri pod sultanovom „milošću"',
    'Putopisi kroz Srbiju',
    'Bitka kod Lepanta i odjeci',
    'Kandijski rat i posledice',
    'Bečki rat 1683.',
  ],
  'hajduci-i-uskoci': [
    'Šta je hajdučija',
    'Uskoci iz Senja',
    'Hajduk Veljko i pre njega',
    'Pjesme i hronike',
    'Mletačka služba uskoka',
    'Hajduci i raja',
    'Manji ustanci u XVI veku',
    'Pograničje između tri carstva',
    'Slavonska Vojna krajina',
    'Vojna granica — život i red',
    'Beg i pljačka',
    'Slika u narodnoj epskoj pjesmi',
  ],
  'velike-seobe': [
    'Pre seoba — XVII vek',
    'Bečki rat i Srbi',
    'Arsenije III Čarnojević',
    'Pisma caru Leopoldu I',
    'Velika seoba 1690.',
    'Krunski hat na Karlovce',
    'Privilegije Srba u Habsburškoj',
    'Posledice po Pećku patrijaršiju',
    'Druga seoba 1737-39.',
    'Arsenije IV',
    'Vojvodina počinje',
    'Identitet u dva carstva',
  ],
  'budenje-pred-ustanak': [
    'Karlovačka mitropolija',
    'Pavle Nenadović',
    'Sava Vladislavić',
    'Zaharija Orfelin',
    'Dositej Obradović',
    'Putovanja Dositeja',
    '„Pismo Haralampiju"',
    'Vuk Karadžić — prvi koraci',
    'Slavjanoserpski jezik',
    'Pred-ustaničke generacije',
    'Kočina krajina',
    'Bačka i Banat u XVIII veku',
  ],

  // ───────────────── Era V — Ustanci ─────────────────
  'prvi-ustanak': [
    'Janičarska samovolja',
    'Seča knezova 1804.',
    'Karađorđe diže ustanak',
    'Orašac, februar 1804.',
    'Prvi sukobi i pobune',
    'Bitka kod Ivankovca 1805.',
    'Bitka na Mišaru 1806.',
    'Oslobođenje Beograda 1806.',
    'Karađorđe i Rusija',
    'Praviteljstvujušči sovjet',
    'Velika narodna škola u Beogradu',
    'Bitka kod Loznice',
    'Pad ustanka 1813.',
    'Bekstvo u Austriju',
    'Posledice prvog ustanka',
  ],
  'drugi-ustanak-i-autonomija': [
    'Pod Sulejman-pašom',
    'Miloš Obrenović',
    'Sastanak u Takovu',
    'Bitka na Ljubiću 1815.',
    'Diplomatska borba sa Portom',
    'Prvi hatišerifi',
    'Ubistvo Karađorđa 1817.',
    'Knjaževina pod osmanskim suverenitetom',
    'Akermanska konvencija 1826.',
    'Jedrenski mir 1829.',
    'Hatišerifi 1830. i 1833.',
    'Knjaz Miloš',
    'Prvi srpski ustav 1835.',
    'Sretenjski ustav',
    'Modernizacija — prvi koraci',
  ],

  // ───────────────── Era VI — Knjaževina i Kraljevina Srbija ─────────────────
  knjazevina: [
    'Knjaz Miloš — apsolutna vlast',
    'Turski ustav 1838.',
    'Abdikacija Miloša',
    'Knjaz Mihailo — prvo vladanje',
    'Ustavobranitelji',
    'Aleksandar Karađorđević',
    'Beogradska škola velikih',
    'Krimski rat i Srbija',
    'Pariski mir 1856.',
    'Svetoandrejska skupština',
    'Povratak Obrenovića 1858.',
    'Smrt Miloša 1860.',
    'Knjaz Mihailo — drugo vladanje',
    'Reforme 1860-ih',
    'Atentat u Topčideru 1868.',
  ],
  'mihailo-i-nezavisnost': [
    'Predaja gradova 1867.',
    'Maloletni Milan Obrenović',
    'Namesništvo',
    'Bosanski ustanak 1875.',
    'Srpsko-turski rat 1876.',
    'Drugi srpsko-turski rat 1877-78.',
    'San Stefano',
    'Berlinski kongres 1878.',
    'Nezavisnost Srbije',
    'Kralj Milan 1882.',
    'Srpska napredna stranka',
    'Rat sa Bugarskom 1885.',
    'Slivnica',
    'Bukureštanski mir 1886.',
    'Kraljica Natalija',
  ],
  'moderna-srbija': [
    'Abdikacija Milana 1889.',
    'Maloletni Aleksandar Obrenović',
    'Aleksandrov državni udar 1893.',
    'Brak sa Dragom Mašin',
    'Majski prevrat 1903.',
    'Petar I Karađorđević',
    'Carinski rat sa Austrijom',
    '„Slučaj Friedjung"',
    'Aneksiona kriza 1908.',
    'Vojna reorganizacija',
    'Nikola Pašić',
    'Radikali i napredni',
    'Aspiracije ka Bosni',
    '„Crna ruka"',
    'Srbija na pragu XX veka',
  ],
  'balkanski-i-veliki-rat': [
    'Balkanski savez 1912.',
    'Prvi balkanski rat',
    'Bitka kod Kumanova',
    'Drugi balkanski rat 1913.',
    'Bukureštanski mir',
    'Sarajevski atentat 1914.',
    'Julski ultimatum',
    'Cerska bitka',
    'Kolubarska bitka',
    'Povlačenje preko Albanije',
    'Albanska golgota',
    'Krf — utočište',
    'Solunski front',
    'Proboj Solunskog fronta',
    'Ujedinjenje 1. decembra 1918.',
  ],

  // ───────────────── Era VII — Jugoslavija ─────────────────
  'kraljevina-shs': [
    'Proglašenje Kraljevine SHS',
    'Privremeno narodno predstavništvo',
    'Vidovdanski ustav 1921.',
    'Atentat na Stjepana Radića',
    'Šestojanuarska diktatura 1929.',
    'Oktroisani ustav 1931.',
    'Naziv Jugoslavija',
    'Atentat na kralja Aleksandra',
    'Marsej 1934.',
    'Knez namesnik Pavle',
    'Pristup Trojnom paktu',
    'Demonstracije i 27. mart 1941.',
    'Britanska i sovjetska politika',
    'Privreda Kraljevine',
    'Kulturni život međuratnog perioda',
  ],
  'drugi-svetski-rat': [
    'Aprilski rat 1941.',
    'Okupacija i podela zemlje',
    'NDH i ustaški režim',
    'Užička republika',
    'Ravna gora — Draža Mihailović',
    'Tito i partizanski pokret',
    'Bitka na Sutjesci',
    'Bitka na Neretvi',
    'AVNOJ — prvo zasedanje',
    'AVNOJ — drugo zasedanje 1943.',
    'Saradnja sa saveznicima',
    'Beogradska operacija 1944.',
    'Sremski front',
    'Oslobođenje Jugoslavije',
    'Posleratni obračun',
  ],
  'socijalisticka-jugoslavija': [
    'Federativna Narodna Republika',
    'Agrarne reforme',
    'Goli otok',
    'Rezolucija Informbiroa 1948.',
    'Tito vs. Staljin',
    'Pokret nesvrstanih',
    'Bandung 1955.',
    'Samoupravljanje',
    'Privredne reforme 1965.',
    'Brionski plenum 1966.',
    'Studentske demonstracije 1968.',
    'Hrvatsko proleće',
    'Ustav iz 1974.',
    'Smrt Tita 1980.',
    'Posle Tita',
  ],
  'kraj-jugoslavije': [
    'Ekonomska kriza 1980-ih',
    'Inflacija i nestašice',
    'Memorandum SANU',
    'Antibirokratska revolucija',
    'Slobodan Milošević',
    'Konflikt na Kosovu',
    'Slovenija i Hrvatska',
    '„Razlaz" Kongresa 1990.',
    'Prvi višestranački izbori',
    'Plebisciti i deklaracije',
    'Sukob u Sloveniji 1991.',
    'Hrvatski rat — početak',
    'Bosanski paralelizmi',
    'JNA na razmeđu',
    'Formalni kraj SFRJ',
  ],

  // ───────────────── Era VIII — Savremena Srbija ─────────────────
  'ratovi-devedesetih': [
    'Rat u Hrvatskoj',
    'Vukovar',
    'Rat u Bosni i Hercegovini',
    'Sankcije UN',
    'Hiperinflacija 1993-94.',
    'Dejtonski sporazum 1995.',
    'Posle Dejtona',
    'Kosovska kriza',
    'NATO bombardovanje 1999.',
    'Kumanovski sporazum',
  ],
  'posle-2000': [
    'Izbori 24. septembra 2000.',
    '5. oktobar 2000.',
    'Zoran Đinđić — premijer',
    'Saradnja sa Haškim tribunalom',
    'Atentat na Đinđića 2003.',
    'Srbija i Crna Gora — državna zajednica',
    'Crna Gora se osamostaljuje 2006.',
    'Proglašenje nezavisnosti Kosova 2008.',
    'Briselski sporazum 2013.',
    'Srbija danas — pitanja koja čekaju',
  ],
};
